name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'packages/is-even-by-cv/**'
      - 'packages/is-odd-by-cv/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: is-even-by-cv
            path: packages/is-even-by-cv
          - name: is-odd-by-cv
            path: packages/is-odd-by-cv
            
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Authenticate with npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # - name: Get current version
      #   run: |
      #     cd ${{ matrix.package.path }}
      #     export CURRENT_VERSION=$(node -pe "require('./package.json').version")
      #   id: version

      # - name: Echo New Version
      #   run: echo "New version is ${{ env.CURRENT_VERSION }}"


      - name: Publish package if changes
        run: |
          cd ${{ matrix.package.path }}
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          if echo "$CHANGED_FILES" | grep -q "${{ matrix.package.name }}"; then
            BUMP_TYPE=$(git log --pretty=format:%s ${{ github.event.before }}..${{ github.sha }} | \
             grep -Ei '^(feat|feature|fix|chore|docs|style|refactor|test|build|release):' | \
             grep -Ei '(feat|feature|minor|fix|release)' | \
             awk '{print tolower($1)}')

            if [ "$BUMP_TYPE" = "release:" ]; then
                BUMP_TYPE="major"
            elif [ "$BUMP_TYPE" = "feat:" ]; then
                BUMP_TYPE="minor"
            elif [ "$BUMP_TYPE" = "fix:" ]; then
                BUMP_TYPE="patch"
            fi

            echo $BUMP_TYPE
            npm version $BUMP_TYPE

            export NEW_VERSION=$(node -pe "require('./package.json').version")
            echo "Publishing version $NEW_VERSION"

            npm publish
           

            echo "Updating local package.json"
            git checkout main
            git branch -a
            git config --local user.email "cvaruncv1998@gmail.com"
            git config --local user.name "cv-arun"
            git add package.json
            git commit -m "Bump version to $NEW_VERSION"
            git push -u origin main
          else
            echo "No changes in ${{ matrix.package.name }}, skipping publish."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}



